language: python
python:
  - 2.7
  - 3.5
install:
  - pip install -r requirements-dev.txt
  - pip freeze
script:
  - make check_lint
  - py.test -vv
after_success:
  - pip install python-coveralls
  - coveralls
